name: Web-tools | Build & Deploy | PROD
on:
  push:
    branches:
      - chore/setup-ci-cd
  release:
    types: [published]
env:
    DOKKU_REMOTE_URL: "ssh://azureuser@ui-1.dev.codeforafrica.org"

concurrency:
    group: "${{ github.workflow }} @ ${{ github.ref }}"
    cancel-in-progress: true

jobs:
    lint-and-test:
        name: Lint and test
        uses: ./.github/workflows/reusable-lint.yml

    build-and-push:
        name: Build and push image to Dockerhub
        needs: lint-and-test
        uses: ./.github/workflows/reusable-build-push.yml
        strategy:
            # Building Multiplatform image takes long (51m), build separate image for staging/prod
            matrix:
                include:
                    - environment: "staging"
                      platforms: "linux/arm64"
                      condition: "github.event_name == 'push'"
                    - environment: "production"
                      platforms: "linux/amd64"
                      condition: "github.event_name == 'release'"
        with:
            image-name: "codeforafrica/civicsignal-web-tools"
            platforms: ${{ matrix.platforms }}
        secrets:
            DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
            SUPPORT_URL: ${{ secrets.SUPPORT_URL }}

    deploy-staging:
        name: Deploy to Staging
        needs: build-and-push
        runs-on: ubuntu-latest
        strategy:
            matrix:
                app: [ civicsignal-explorer ]
        if: github.event_name == 'push'
        steps:
          - name: Deploy ${{ matrix.app }} to staging
            uses: dokku/github-action@v1.7.0
            with:
                deploy_docker_image: ${{ needs.build-and-push.outputs.image-name }}
                deploy_user_name: ${{ github.actor}}
                deploy_user_email: ${{ github.actor }}@github-workflow.codeforafrica.org
                git_remote_url: ${{ env.DOKKU_REMOTE_URL }}/${{ matrix.app }}
                ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
