name: Web-tools | Build & Deploy | PROD
on:
  push:
    branches:
      - chore/setup-ci-cd
env:
    DOKKU_REMOTE_URL: "ssh://dokku@api-1.dev.codeforafrica.org/trustlist"

concurrency:
    group: "${{ github.workflow }} @ ${{ github.ref }}"
    cancel-in-progress: true

jobs:
    lint-and-test:
        uses: ./.github/workflows/reusable-lint.yml

    build-and-push:
        uses: ./.github/workflows/reusable-build-push.yml
        with:
            image-name: "codeforafrica/web-tools"
        secrets:
            DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
            SUPPORT_URL: ${{ secrets.SUPPORT_URL }}

    # deploy:
    #     needs: build-and-push
    #     if: needs.build-and-push.outputs.version-changed == 'true'
    #     uses: ./.github/workflows/reusable-deploy.yml
    #     with:
    #         dokku-remote-url: "ssh://dokku@your-server.com/your-app-name"
    #         image-name: ${{ needs.build-and-push.outputs.image-name }}
    #         image-tag: ${{ needs.build-and-push.outputs.image-tag }}
    #         environment: "production"
    #         secrets:
    #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
