name: Pull request workflow
on:
    pull_request:
        types: [opened, synchronize, reopened]

concurrency:
    group: "pull-request-${{ github.event.pull_request.number }}"
    cancel-in-progress: true

jobs:
    setup-node:
        uses: ./.github/actions/setup-node

    setup-python:
        uses: ./.github/actions/setup-python

    lint-and-test:
        needs: [setup-node, setup-python]
        uses: ./.github/workflows/reusable-lint.yml
        secrets: inherit

